version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup_remote_docker
      - run:
          name: Run build
          command: yarn build

  deploy-production:
    docker:
      - image: cimg/node:20.18
    steps:
      - add_ssh_keys:
          fingerprints:
            - "2b:a3:fb:10:f8:60:9a:78:8d:5f:02:51:76:43:b3:86"
      - run:
          name: Add to known hosts
          command: ssh-keyscan -H 203.161.46.54 >> ~/.ssh/known_hosts
      - run:
          name: Deploy Application via SSH
          command: |
            ssh -o ConnectTimeout=10 -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa_2ba3fb10f8609a788d5f02517643b386 root@203.161.46.54"
              cd /home/webapp/swapforge &&
              sudo npm i -g pm2 yarn &&
              pm2 deploy ../ecosystems/swapforge-ecosystem.config.js production
            "

workflows:
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - main

  production:
    jobs:
      - build-and-test:
          filters: &filters-production
            branches:
              only: main
      - deploy-production:
          filters:
            <<: *filters-production
          requires:
            - 'build-and-test'