version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/.cache/yarn
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Run build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - build
            - node_modules

  deploy-production:
    docker:
      - image: cimg/node:18.17
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run:
          name: Add to known hosts
          command: ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
      - run:
          name: Install pm2
          command: sudo npm i -g pm2
      - run:
          name: Deploy to VPS Namecheap
          command: pm2 deploy production

workflows:
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - main

  production:
    jobs:
      - build-and-test:
          filters: &filters-production
            branches:
              only: main
      - deploy-production:
          filters:
            <<: *filters-production
          requires:
            - 'build-and-test'