version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup_remote_docker
      - run:
          name: Run build
          command: yarn build

  deploy-production:
    docker:
      - image: cimg/node:20.18
    steps:
      - add_ssh_keys:
          fingerprints:
            - $SSH_FINGERPRINT
      - run:
          name: Check fingerprints
          command: echo $SSH_FINGERPRINT
      - run:
          name: Check Host
          command: echo $VPS_IP      
      - run:
          name: Add to known hosts
          command: ssh-keyscan -H $VPS_IP >> ~/.ssh/known_hosts
      - run:
          name: Install pm2
          command: sudo npm i -g pm2
      - run:
          name: Deploy to VPS Namecheap
          command: pm2 deploy production

workflows:
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - main

  production:
    jobs:
      - build-and-test:
          filters: &filters-production
            branches:
              only: main
      - deploy-production:
          filters:
            <<: *filters-production
          requires:
            - 'build-and-test'
