version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:22.14
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run build
          command: yarn build

  deploy:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - 'SHA256:uPAJsXgbS3As3+NN97LYxt1PFtmQTAU2DG0GWErjB5A'
      - run:
          name: Setup SSH config
          command: |
            mkdir -p ~/.ssh
            echo "Host swapforge-server" >> ~/.ssh/config
            echo "  HostName 203.161.38.116" >> ~/.ssh/config
            echo "  User root" >> ~/.ssh/config
            echo "  IdentityFile ~/.ssh/id_rsa_*" >> ~/.ssh/config
            echo "  StrictHostKeyChecking no" >> ~/.ssh/config
            chmod 600 ~/.ssh/config
      - run:
          name: Deploy to server
          command: |
            set -e

            echo "🚀 Starting deployment to SwapForge server..."

            # Create deployment directory if it doesn't exist
            ssh swapforge-server "mkdir -p /home/webapp/swapforge"

            # Backup current deployment
            ssh swapforge-server "cd /home/webapp && [ -d swapforge/current ] && cp -r swapforge/current swapforge/backup.\$(date +%Y%m%d_%H%M%S) || true"

            # Sync the built application
            echo "📦 Syncing application files..."
            rsync -avz -e "ssh" \
              --exclude='.env*' \
              --exclude='node_modules' \
              --exclude='.git' \
              ~/project/web-app/ \
              swapforge-server:/home/webapp/swapforge/current/

            # Copy environment file
            echo "🔧 Setting up environment..."
            ssh swapforge-server "cp /home/webapp/swapforge/.env /home/webapp/swapforge/current/"

            # Install dependencies and restart
            echo "⚙️ Installing dependencies and starting application..."
            ssh swapforge-server "cd /home/webapp/swapforge/current && \
              export APP_ENV=production && \
              yarn install --production --frozen-lockfile && \
              yarn build && \
              cd /home/webapp/swapforge && \
              pm2 reload ecosystem.config.js --env production && \
              pm2 save && \
              echo '✅ Deployment completed successfully!'"

            echo "🎉 SwapForge deployment completed!"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
