version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup_remote_docker
      - run:
          name: Run build
          command: yarn build
      - persist_to_workspace:
          root: .
          paths: .

  deploy:
    machine:
      image: ubuntu-2204:edge
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - 'S0V13pVA2H11zkJ1o7ixLfo78Hvz18bOGurDCzIjZwQ'
      - run:
          name: Install SSH dependencies
          command: sudo apt-get update && sudo apt-get install -y openssh-client rsync
      - run:
          name: Setup SSH config
          command: |
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run:
          name: Verify SSH Access
          command: ssh -v $SSH_USER@$SSH_HOST "echo 'SSH connection successful!'"
      - run:
          name: Direct Deployment
          command: |
            rsync -avz -e ssh --delete \
              --exclude='node_modules' \
              --exclude='.git' \
              ./ $SSH_USER@$SSH_HOST:/home/webapp/swapforge/
            
            ssh $SSH_USER@$SSH_HOST "
              cd /home/webapp/swapforge && \
              yarn install --production && \
              pm2 restart ../ecosystems/swapforge-ecosystem.config.js
            "

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main