version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup_remote_docker
      - run:
          name: Run build
          command: yarn build

  deploy:
    machine:
      image: ubuntu-2204:edge
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'S0V13pVA2H11zkJ1o7ixLfo78Hvz18bOGurDCzIjZwQ'
      - run:
          name: Deploy using SSH
          command: | 
            ssh -o StrictHostKeyChecking=no -o BatchMode=yes $SSH_USER@$SSH_HOST "cd /home/webapp/swapforge && sudo npm i -g pm2 yarn && pm2 deploy ../ecosystems/swapforge-ecosystem.config.js production"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main