version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build:
    docker:
      - image: cimg/node:22.14
    working_directory: ~/project/web-app
    steps:
      - checkout:
          path: ~/project
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run build
          command: yarn build

  deploy:
    machine:
      image: ubuntu-2204:2024.01.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - add_ssh_keys:
          fingerprints:
            - 'S0:V1:3p:VA:2H:11:zk:J1:o7:ix:Lf:o7:8H:vz:18:bO'
      - run:
          name: Deploy to server
          command: |
            set -e  # Exit on any error

            echo "Starting deployment to $SSH_HOST..."

            # Create deployment directory if it doesn't exist
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "mkdir -p /home/webapp/swapforge"

            # Create backup of current deployment
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST \
              "cd /home/webapp && [ -d swapforge ] && cp -r swapforge swapforge.backup.$(date +%Y%m%d_%H%M%S) || true"

            # Sync the built application (excluding sensitive files)
            rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
              --exclude='.env*' \
              --exclude='node_modules' \
              ~/project/web-app/ \
              $SSH_USER@$SSH_HOST:/home/webapp/swapforge/

            # Install dependencies and restart the application
            ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST \
              "cd /home/webapp/swapforge && \
               export APP_ENV=production && \
               npm install -g pm2 yarn && \
               yarn install --production --frozen-lockfile && \
               pm2 startOrRestart ecosystem.config.js --env production && \
               pm2 save && \
               echo 'Deployment completed successfully'"

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
