version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.18
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - setup_remote_docker
      - run:
          name: Run build
          command: yarn build

  deploy-production:
    docker:
      - image: cimg/node:20.18
    steps:
      - add_ssh_keys:
          fingerprints:
            - 'S0V13pVA2H11zkJ1o7ixLfo78Hvz18bOGurDCzIjZwQ'
      - run:
          name: Deploy using SSH
          command: | 
            ssh -o StrictHostKeyChecking=no -o BatchMode=yes $SSH_USER@$SSH_HOST "cd /home/webapp/swapforge && sudo npm i -g pm2 yarn && pm2 deploy /home/webapp/swapforge/ecosystem.config.js production"

workflows:
  build:
    jobs:
      - build-and-test:
          filters:
            branches:
              ignore:
                - main

  production:
    jobs:
      - build-and-test:
          filters: &filters-production
            branches:
              only: main
      - deploy-production:
          filters:
            <<: *filters-production
          requires:
            - 'build-and-test'
